src/hu_stuff.c

Figured out this bug while porting the status bar to the Nintendo Wii port of Chocolate DOOM.

Endianness related change to patch width

---

src/c_cmds.c
src/d_iwad.c
src/d_main.c
src/m_misc.c
src/m_misc.h

This pull request makes DR save its user-generated files (configs, logs, savegames) into the appropriate per-user Application Support folder on OSX, rather than saving them to the folder the app is located in. It also adds a suitable hook for Windows and Linux builds to do the same: e.g. Windows ought to save to "%APPDATA%\Doom Retro", while Linux should probably save to "~/.doomretro". (I have not changed the behaviour for those platforms though.)
This behaviour is necessary because OSX apps are not kept in folders of their own - they are self-contained bundles that are typically stored in a single Applications folder alongside many other apps. Rather than write to their location, apps are expected to write to specific per-user folders - and indeed the app's containing folder may be …

OSX: Save user files into Application Support instead of app location.

---

src/d_main.c
src/i_main.c
src/r_data.c
src/r_things.c

I've removed all warnings I get during compilation by removing some unecessary brackets and by adding one forward declaration and some trivial casts.
(2nd try. Sorry about that.)

Removed warnings (gcc 5.3.0)

---

src/i_video.c

Moved UpdateFocus() and UpdateGrab() to bottom of I_InitGraphics() to fix the visible mouse pointer problem on Linux with SDL 2.0.4

Possible fix for the mouse pointer issue

---

src/Makefile
src/m_misc.c
src/m_misc.h
src/w_file.h

the ```m_misc.h``` fix adding ```<stdarg.h>``` resolves a very long-standing problem I've always had with compilation regarding ```va_list```.  i used to just quickly hack-fix it by prefixing ```__``` to ```va_list``` in ```m_misc.h```, until i found what seems to be a better way.  i believe stdarg.h is rather standard, might not hurt to always have it enabled but i guarded it to be safe.
same goes for the ```m_misc.c``` and ```w_file.h``` fixes.  these may be wanted on all platforms, if so we can simply remove the ```#if defined(__OpenBSD__)``` parts or at least restrict to 'if not windows...' for example..
Only the ```Makefile``` fix I'm pretty sure we want this on all platforms that use ```Makefile``` :)
Each commit message contains the error message resolved.

fix a few issues

---

AUTHORS

That's me. I'd prefer to be credited using my real name please.

Switches a contributor's credit from GitHub/Twitter handle to real name.

---

src/m_menu.c

I'm not sure if this is the best way to do it, but this gets the PrtScn key working in Linux.
Before this commit, the PrtScn key has not effect in Linux. Not even after "bind printscreen +screenshot".
After this commit, "bind printscreen +screenshot" makes the PrtScn key takes screenshots when Doom Retro is running in Linux.

Prtsc key works in Linux

---

src/d_main.c

I've tested this on Linux with Breach, and with Alien Vendetta with both lowercase and uppercase filenames.
Disclaimer: I haven't tested on Windows.

Finding the matching DEH/BEX file for a WAD is case-insensitive on POSIX.

---

src/d_main.c

Accounts for wordexp not being available on OpenBSD. As per this thread:
https://github.com/bradharding/doomretro/commit/f85031c0887fd11b20df26f9ad2bd1f696f09dfc#commitcomment-18717630

Accounts for wordexp not being available on OpenBSD

---

src/d_main.c

This fixes the substitution used to case-insensitively find deh and beh files for a wad.
The issue was pointed out here:
https://github.com/bradharding/doomretro/commit/24560539649d08f70ddba55c1ddebe0c48e3d07a#commitcomment-18804765

dehpattern substitution fixed

---

src/m_misc.c

fix:
```
cc -O2 -g `sdl2-config --cflags` -DX11 -c m_misc.c -o m_misc.o
m_misc.c: In function 'M_GetAppDataFolder':
m_misc.c:184: error: 'DIR' undeclared (first use in this function)
m_misc.c:184: error: (Each undeclared identifier is reported only once
m_misc.c:184: error: for each function it appears in.)
m_misc.c:184: error: 'resourceDir' undeclared (first use in this function)
m_misc.c: In function 'M_GetResourceFolder':
m_misc.c:223: error: 'DIR' undeclared (first use in this function)
m_misc.c:223: error: 'resourceDir' undeclared (first use in this function)
gmake: *** [Makefile:58: m_misc.o] Error 1
```

fix compilation on OpenBSD

---

src/p_fix.c

Must be good enough for fixing nukage textures on MAP18.
Line 17: http://i.imgur.com/aHayPnx.png
Line 18: http://i.imgur.com/Jf3K8mo.png

Small fix for missing nukage graphics on MAP18

---

src/p_fix.c

More to come, of course, but I see that Plutonia is well polished already.
- **Map 01**
Linedef 1110: fixed offsets of the red key wall texture.
http://i.imgur.com/iGV5VC7.png
- **Map 04**
Linedef 975: fixed offset of the exit-like doorway.
http://i.imgur.com/ODLL6k2.png
- **E4M7**
Linedefs 989 and 991: I have forgot them to previous commit, sorry. It makes vertical alignment more proper, but it's hard to show them both in one screenshots, it's opposite walls.
http://i.imgur.com/ZCB5L4S.png

Various level-specific fixes for Plutonia (part 1)

---

src/p_fix.c

There is few important moments, please pay attention.
- **MAP12**
Linedef 230: this linedef have missing "impassible" flag. I have not touched it, because it's beloved by speed runners. Just FYI, maybe it will be better to leave this "as is".
- **MAP16**
Sectors 97 and 104: fixed incorrect ceiling textures. Player will see them without free look, so maybe it will be good for future, in case of one day Doom Retro will have free mouse look.
http://i.imgur.com/daw4N2G.png <br />
**Attention needed:** There is a known problem in exit room. If player will fall down from these sectors (http://i.imgur.com/3PfAU6X.png) to the slime, there will be no way back, since slime is not damaging and there is no teleport back. Only `idclip` will help.<br />
I see two ways to fix it:
<br />1. Add super …

Various level-specific fixes for Plutonia (part 2)

---

src/p_fix.c

Here we go, final part 3.
- **MAP22**
Linedefs 1026 and 1028: Some nicer offets for the bottom of nukage walls
Nothing I can do on the opposite side, though - changing vertical offsets simply makes metal grate texture goes away.
http://i.imgur.com/BAJu9ND.png
- **MAP28**
Linedefs 1232, 1233, 1234, 1233: four lamp textures lowered down to 1px.
http://i.imgur.com/xb5jNS6.png
- **MAP29**
Sector 178: floor height increased just few map units high to make a skull textures looking proper. Texture offset correction is not working here due to wall height.
http://i.imgur.com/qCHttLJ.png
Sector 224: same as above.
http://i.imgur.com/WQPaep9.png
Linedefs 1144, 1147, 1150: nicer and centered offsets, please, it's a living-like building!
http://i.imgur.com/ddg0UvD.png
Linedefs 2936 and 2938: little …

Various level-specific fixes for Plutonia (part 3)

---

src/c_cmds.c
src/d_main.c

D_FindIWAD makes the previous malloc call lose the address.

small memory leaks fixes:

---

.travis.yml

Improvements to continuous integration:
- cmake 3 is now installed from the official repositories (this results in much faster builds!)
- it's now built using both clang and gcc
Please note that because we're now also building with GCC, this now  tests only the CMake build. As src/Makefile doesn't (currently) work with Ubuntu Trusty's GCC, I've removed it from the CI build steps (for now).
References:
- https://github.com/bradharding/doomretro/issues/341
- https://github.com/bradharding/doomretro/issues/300

CI builds using clang and gcc

---

src/d_main.c

"'NSFileHandlingPanelOKButton' is deprectaed: first deprecated in macOS 10.13
Replace 'NSFileHandlingPanelOKButton' with 'NSModalResponseOK'"

Fix for deprecated function

---

src/d_main.c

Code was not checking to see if an iwad had already been found and was therefore adding doom2.wad even when plutonia.wad or tnt.wad were already found. See Issue https://github.com/bradharding/doomretro/issues/418

Fix for non doom and doom2 pwads

---

src/r_plane.h

@bradharding was correct in this issue assuming PL_SKYFLAT might not need to be lowered down.
However the original appears to be too low for some.
Indeed, after having spent more time trying out few pwad it appears most of the time images data were read beyond their real size so on Mac sometimes it worked but should not but having enabled proper memory boundaries checkers ... it crashed as mainly PL_SLYFLAT mask appeared to be to low.
Please @bradharidng and possibly @jasoncarlough tries out few pwad on your own side to see if it really fixes.
Sorry for inconveniences.

reverting my proposition for the issue #418

---

src/d_main.c
xcode/doomretroapp.xcodeproj/project.pbxproj

When attempting to run a pwad without first selecting any iwads, the wad launcher was printing the error message "couldn't find" pwad.wad instead of "couldn't find any IWADs"

Wad launcher giving wrong error message

---

src/p_switch.c
src/r_bsp.c

I'm a member of the Pinguem.ru competition on finding errors in open source projects. Warnings, found using PVS-Studio:
doomretro/src/r_bsp.c       276     warn    V547 Expression 'underwater' is always true.
doomretro/src/p_switch.c    280     warn    V560 A part of conditional expression is always true: !side.
doomretro/src/p_switch.c    286     warn    V547 Expression '!side' is always true.

Fixed conditions

---

src/r_data.c
src/wi_stuff.c

I like your project and I'm exploring it as part of the competition the Pinguem.ru competition on finding errors in open source projects. New warnings, found using PVS-Studio:
doomretro/src/r_data.c      708     warn    V575 The potential null pointer is passed into 'memset' function. Inspect the first argument.
doomretro/src/wi_stuff.c    375     warn    V728 An excessive check 'i > 0' can be simplified. The '||' operator is surrounded by opposite expressions.

New static analyser issues 

---

src/r_data.c

there was an overflow ocuring while writing into the array.

overflow fix proposal. dboolean being int's large sized,

---

src/d_iwad.c
src/m_config.h

- default folder when platforms != WIN32
- trying to escape the folder value when this is not user provided
as int this case it s a constant (write access mem issue).

try to fix two little issues :

---

src/c_console.c
src/d_deh.c
src/d_iwad.c
src/d_main.c
src/i_video.c
src/m_config.c
src/m_misc.c
src/r_data.c
src/v_video.c
src/w_wad.c

Don't merge this yet. I'm going to build this up with a bunch of commits fixing memory leaks. I'll document the ones being fixed as I go. Here's the first set:
```
==14544== 3 bytes in 1 blocks are definitely lost in loss record 16 of 2,400
==14544==    at 0x5550B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==14544==    by 0x63199B9: strdup (strdup.c:42)
==14544==    by 0x18933B: commify (in /usr/local/bin/doomretro)
==14544==    by 0x17FA2F: M_LoadCVARs (in /usr/local/bin/doomretro)
==14544==    by 0x16AC2F: D_DoomMainSetup (in /usr/local/bin/doomretro)
==14544==    by 0x16C36D: D_DoomMain (in /usr/local/bin/doomretro)
==14544==    by 0x16C39D: main (in /usr/local/bin/doomretro)
==14544== 
==14544== 3 bytes in 1 blocks are definitely lost in loss record 17 of 2,400 …
```

Many memory leak fixes

---

src/c_autocomplete.c
src/c_cmds.c
src/d_iwad.c
src/d_main.c
src/i_video.c
src/m_config.c
src/m_config.h
src/m_menu.c
src/m_misc.c
src/v_video.c

I made a few changes to get the current state of the repository compiling and running on macOS:
- There were a couple of filename helper functions (specifically `D_IsCfgFile` and `D_IsDehFile`) that were missing when compiled for anything other than windows. These seemed pretty innocent and were used in locations that were not being wrapped in OS macros anyway.
- Wrapped a reference to `previouswad` in a Windows macro as it was being referenced for all OS targets when it was only originally defined for Windows.
- Removed a `free()` allocation call in `V_Init` when running on mac. This was something added in this pull request: #509. However, based on the comments in the pull request this was unable to be tested on mac? Well this particular `free()` was causing a signal abort crash on mac. …

Fix compiling on mac for Doom Retro 3.0

---

src/m_config.h

`m_config` `wad` was not being defined on mac during compilation despite it being referenced elsewhere in the codebase on mac.

Fixed building on mac

---

src/f_finale.c
src/g_game.c
src/p_setup.c
src/wi_stuff.c

Pair next = "endgamec" used in some PWADs for the end game. Avactor map12 for example.

Add EndGameC support to MAPINFO

---

src/m_misc.c
src/m_misc.h

Fixes wrong free usage from GetExecutableFolder from dirname.
On NetBSD dirname being reentrant, using a buffer as output
thus losing original address in our case.

Completes NetBSD support.

---

src/i_music.c
src/i_sound.c
src/s_sound.h

Native media sound system of Haiku triggers segfault if NULL for the device name is provided.
Similarly, the mixer frequency needs a value before being set afterwards.

Sound system fix for haiku.

---

src/m_menu.c

Tested with Doom 2, it crashes once the menu launches.

Prevents blurscreen1 data writing subtle overflow.

---

src/i_video.c

Fix for issue #484 
When SDL_SetRelativeMouseMode is called mid-mouse click, the corresponding SDL_MOUSEBUTTONUP appears not to fire and it would behave as though mouse button 1 was stuck down. Calling SDL_PumpEvents beforehand appears to push the event through.

Fix for constant weapon fire on game load when clicking through menus

---

src/i_video.c

In response to the discussion at #650 , this changes the `translatekey` array during `I_InitGraphics` to match the keyboard layout (at least on alphanumeric characters and bind-able punctuation). Tested to work on Debian 10 and Arch.
I believe it's something of a hack as the present system is too inflexible. Also something in the key-handling logic depends sensitively on one or more zeroes in that array, so we can't rewrite the whole thing according to the layout, hence the odd loop indices.
A full solution would involve dispensing with the current input handling method and maintaining instead an associative list of `SDLK_*` keycodes to values. I would understand rejecting this on these grounds.

Populate translatekey table based on keyboard layout

---

src/i_video.c

Hi @bradharding 
The SDL2 docs specify that you must do an SDL_RenderClear() call before a SDL_RenderCopy() call or a series of them, or the state of the renderer is "unknown" since you did the previous SDL_RenderPresent() call.
(You may not have seen the consequences of this omission, but in KMSDRM it's very apparent that frames repeat, etc... causing a dizzy movement without this).
So, this patch addresses the issue.

Add missing SDL_RenderClear() calls.

---

src/d_iwad.c

doomretro was crashing on startup.
Exception code:0xc0000374 according to Event Viewer.
This PR fixes that problem.

fix potential heap corruption (calling free on string literal)

---

src/Makefile.osx

64bit only since MacOS is no longer 32bit capable unless you run an older OS.  Long term support is not worth it.
I added the -ObjC flag because d_main is calling Cocoa.  Without this, the C compiler will attempt to read the header as a C header, not as an ObjC header.  This fixes the issue by telling the compiler to treat it as Objective C if it finds any headers that are in that language.

Fix building on MacOS

---

src/Makefile.mingw

This allows Doom Retro to be compiled using MinGW on Windows.  Tested and Doom Retro functions just fine afterwards.

Adding MinGW makefile

---

.github/workflows/build.yml
scripts/build.sh

Build on clang and gcc to keep compatibility with those compilers. Bulk
of script written in shell script to avoid vendor lock-in, makes it
easier to switch between Travis, Github Actions, Cirrus, etc.

Setup Github Action

---

src/d_main.c
src/m_misc.c

data was allocated on the heap but the returned data weren't
thus during IWAD data load it crashes (d_iwad part).

macos M_GetExecutableFolder bug fix proposal.

---

src/doomdef.h
src/z_zone.h

here we try to avoid Z_Malloc/free calls mismatches sort of situations
as well.

new ALLOC*ATTR fn attribute.

---

src/m_misc.c

unlike lowercase, uppercase works on
a copy.

M_FileCaseExists fix proposal.

---

src/p_spec.h

The problem occurs when trying to build a game using X11.
There is such a line in the X11/X.h file:
```c
/*****************************************************************
* RESERVED RESOURCE AND CONSTANT DEFINITIONS
*****************************************************************/
...
#define AnyKey     0L /* special Key Code, passed to GrabKey */
```
At the same time, in the doomretro code, there is the following enum in the p_spec.h file:
```c
// define names for the locked door Kind field of the general ceiling
enum
{
AnyKey,
...
};
```
Include chain:
```text
i_video.c:37: #include <X11/Xlib.h>
/usr/include/X11/Xlib.h:44: #include <X11/X.h>
i_video.c:55: #include "m_config.h"
m_config.h:39: #include "p_local.h"
p_local.h:341: #include "p_spec.h"
```
Therefore, a problem occurs when …

FIX: build when using X11

---

src/d_iwad.c
src/m_misc.c

IWAD search was not working properly undercertain conditions:
- DirIsFile: returning true with arguments path="/usr/share/doom" filename="doom", which is bogus. Now check if directory really points to a wad file.
- M_FileCaseExists: did not work properly when the first trivial test is false

fix IWAD search path issues on platforms other that Windows and macOS

---

src/m_config.c

with the wadfolder with a value of '/', it was attempted to truncate at PATH_MAX.

cmd buffer overflow proposal.

---

src/p_setup.c
src/p_spec.c
src/p_switch.c
src/r_defs.h
src/r_main.c

Tested in both my own test WAD and boomtest, works under the use-cases I've tried so far without issue. Does *not* override player colormaps (damage, powerups) as per spec, overrides other colormaps like transfer heights as per spec, and defaults to the normal colormap (or whatever transfer colormap is active via line 242) if the colormap is invalid.

Id24 colormaps
