.gitignore
src/d_main.c
src/m_menu.c
xcode/doomretroapp.xcodeproj/project.pbxproj

Most of changes are required for building Doom Retro on OS X using Xcode project.

Various fixes for OS X

---

.travis.yml

Sets Doom Retro up for Travis CI integration. #286

Travis build configuration added

---

src/d_main.c

Further testing showed that this is needed.

Further fix to get deh/bex matches working

---

src/c_console.c
src/hu_lib.c
src/p_enemy.c
src/r_bsp.c

Reverts the commit that caused #295

Revert the commit that caused #295

---

src/m_misc.c

This is to address the recommendation in #300 
On Linux and OSX, if the build is portable, then write the CFG file into the executable directory and expect it there. Otherwise, write it to and read it from ~/.config/doomretro/doomretro.cfg as before.

Portable builds have the cfg file in the executable directory.

---

src/m_misc.c

Looks like a comment got cut off. This new commit just completes the comment.

Comment completed

---

src/c_cmds.c
src/d_iwad.c
src/d_main.c
src/w_wad.c

Restore https://github.com/bradharding/doomretro/pull/280

IWAD names are expected to be uppercase

---

src/m_misc.c

FreeBSD build fix plus FreeBSD is capable to

---

src/m_misc.c

Here a proposal to fix those not sure it will be accepted as it is can be freely changed :-)

Proposal to fix unavoidable mem leak for the various log messages.

---

src/m_misc.c
xcode/doomretroapp.xcodeproj/project.pbxproj

I wasn't able to compile the last few OS X builds (last working release was 2.5.2). I fixed it by making a couple of small changes.

changes for OS X build

---

src/doom/info.c

This fixes the Xcode build, I don't know what it does to any other builds though.

Fix for the Xcode build

---

xcode/doomretroapp.xcodeproj/project.pbxproj

Fix broken references in Xcode project to resolve #464

Fix macOS build

---

src/f_finale.c

Also, fix some errors in UMAPINFO files: [umapinfo.zip](https://github.com/bradharding/doomretro/files/5047185/umapinfo.zip)

Fix intertext clear

---

src/g_game.c
src/m_menu.c

See https://github.com/bradharding/doomretro/issues/607#issuecomment-681195243

Fix custom episodes in DOOM1

---

src/m_misc.c

More straightforward way to get the current binary full path.

Haiku M_GetExecutableFolder little code simplification,

---

src/m_config.c

segfault occuring on Mac M1 (at least), so we copy the data before

---

src/m_menu.c

In some cases offset calculations, it was negative, crashing after launching new party.
detected with DOOM2

Fix buffer overflow at load time.

---

src/m_misc.c

for FreeBSD/DragonFlyBSD and Haiku this time.

M_GetExecutableFolder catching up on previous changes with macOs

---

src/p_mobj.c

proposing to delay it instead.

UAF case found when blood splats, pb is the object is freed right away,

---

src/d_deh.c

checking before if there is still data to fetch before accessing the buffer, before the size became negative.

dehfgets heap overflow fix proposal.
